name: sylph
description: A utility for running Flutter integration tests on pools of real devices in cloud. Works with AWS Device Farms.
version: 0.7.3
homepage: https://github.com/mmcc007/sylph

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  args: ^2.3.2
  collection: ^1.14.12
  duration: ^2.0.8
  isolate: ^2.1.1
  path: ^1.6.2
  process: ^4.2.4
  resource: ^2.1.5
  sprintf: ^4.0.2
#  tool_base: ^1.9.6
  tool_base:
    git: https://github.com/tek08/tool_base.git
#    path: ../tool_base
  version: ^1.0.3
  yaml: ^3.1.1
  yamlicious: ^0.1.0

dev_dependencies:
#  fake_process_manager: ^0.1.1
  fake_process_manager:
    git: https://github.com/tek08/fake_process_manager.git
#    path: ../fake_process_manager
  file: ^6.1.4
  mockito: ^5.3.2
  pedantic: ^1.8.0+1
  test: ^1.22.2
#  tool_base_test: ^1.0.1
  tool_base_test:
    git: https://github.com/tek08/tool_base_test.git
#    path: ../tool_base_test

executables:
  sylph: main