name: flavors
description: Integration test for build flavors.
version: 0.0.1

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.21.4

flutter:
  uses-material-design: true
